[package]
name = "danmaku_reborn"
version = "0.1.0"
edition = "2021"
authors = ["Code Monad",]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bili-api-authentication = { path = "./authentication" }